---
services:
  asap-cli:
    build:
      context: ./asap-cli
      dockerfile: Dockerfile
    container_name: asap-dev-asap-cli
    hostname: asap-cli
    image: asap-cli:latest
    environment:
      ASAP_LOGGER_ENABLE: true
      ASAP_LOGGER_KAFKA_BROKERS: kafka-broker:9092

  asap-db:
    image: postgres:17
    container_name: asap-db
    hostname: asap-db
    environment:
      POSTGRES_USER: asap
      POSTGRES_PASSWORD: asap_pwd
      POSTGRES_DB: asap
    volumes:
      - asap-db-data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: unless-stopped

  asap-kafka-consumer:
    build:
      context: ../asap-api
      dockerfile: Dockerfile
    container_name: asap-dev-asap-kafka-consumer
    hostname: asap-kafka-consumer
    image: asap-api:latest
    environment:
      ASAP_DB_HOST: asap-db
      ASAP_DB_PORT: 5432
      ASAP_DB_NAME: asap
      ASAP_DB_USER: asap
      ASAP_DB_PASSWORD: asap_pwd
      ASAP_KAFKA_BROKERS: kafka-broker:9092
    ports:
      - "8000:8000"
    depends_on:
      - asap-db
      - kafka-broker

  kafka-broker:
    container_name: asap-dev-kafka-broker
    hostname: kafka-broker
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    expose:
      - "9092"

  debian11:
    build:
      context: ./os/debian
      dockerfile: Dockerfile.debian11
    container_name: asap-dev-debian11
    hostname: debian11
    image: asap-dev-debian:11
    expose:
      - "22"

  debian12:
    build:
      context: ./os/debian
      dockerfile: Dockerfile.debian12
    container_name: asap-dev-debian12
    hostname: debian12
    image: asap-dev-debian:12
    expose:
      - "22"

  debian13:
    build:
      context: ./os/debian
      dockerfile: Dockerfile.debian13
    container_name: asap-dev-debian13
    hostname: debian13
    image: asap-dev-debian:13
    expose:
      - "22"

  fedora39:
    build:
      context: ./os/fedora
      dockerfile: Dockerfile.fedora39
    container_name: asap-dev-fedora39
    hostname: fedora39
    image: asap-dev-fedora:39
    expose:
      - "22"

  fedora40:
    build:
      context: ./os/fedora
      dockerfile: Dockerfile.fedora40
    container_name: asap-dev-fedora40
    hostname: fedora40
    image: asap-dev-fedora:40
    expose:
      - "22"

  fedora41:
    build:
      context: ./os/fedora
      dockerfile: Dockerfile.fedora41
    container_name: asap-dev-fedora41
    hostname: fedora41
    image: asap-dev-fedora:41
    expose:
      - "22"

  fedora42:
    build:
      context: ./os/fedora
      dockerfile: Dockerfile.fedora42
    container_name: asap-dev-fedora42
    hostname: fedora42
    image: asap-dev-fedora:42
    expose:
      - "22"

  ubuntu1804:
    build:
      context: ./os/ubuntu
      dockerfile: Dockerfile.ubuntu1804
    container_name: asap-dev-ubuntu1804
    hostname: ubuntu1804
    image: asap-dev-ubuntu:18.04
    expose:
      - "22"

  ubuntu2004:
    build:
      context: ./os/ubuntu
      dockerfile: Dockerfile.ubuntu2004
    container_name: asap-dev-ubuntu2004
    hostname: ubuntu2004
    image: asap-dev-ubuntu:20.04
    expose:
      - "22"

  ubuntu2204:
    build:
      context: ./os/ubuntu
      dockerfile: Dockerfile.ubuntu2204
    container_name: asap-dev-ubuntu2204
    hostname: ubuntu2204
    image: asap-dev-ubuntu:22.04
    expose:
      - "22"

  ubuntu2404:
    build:
      context: ./os/ubuntu
      dockerfile: Dockerfile.ubuntu2404
    container_name: asap-dev-ubuntu2404
    hostname: ubuntu2404
    image: asap-dev-ubuntu:24.04
    expose:
      - "22"

volumes:
  asap-db-data:
