FROM debian:12@sha256:26f2a7cab45014541c65f9d140ccfa6aaefbb49686c6759bea9c6f7f5bb3d72f

RUN apt-get update \
    && apt-get install -y openssh-server sudo supervisor \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create 'asap' user with sudo privileges
RUN adduser --system --disabled-password --shell /bin/bash --home /home/asap --group asap \
    && mkdir -p /home/asap/.ssh \
    && usermod -aG sudo asap \
    && sed -i -E 's/%sudo\s+ALL=\(ALL:ALL\) ALL/%sudo ALL=\(ALL:ALL\) NOPASSWD:ALL/g' /etc/sudoers

# Add SSH public key for 'asap' user
COPY id_ed25519.pub /home/asap/.ssh/authorized_keys
RUN chown -R asap:asap /home/asap/ \
    && chmod 700 /home/asap/.ssh \
    && chmod 600 /home/asap/.ssh/authorized_keys

# Requirements for SSH daemon
RUN mkdir /run/sshd && chmod 0755 /run/sshd

# Copy supervisord configuration
COPY supervisord.conf /etc/supervisord.conf

ENTRYPOINT [ "/usr/bin/supervisord", "-c", "/etc/supervisord.conf" ]

LABEL org.opencontainers.image.title="ASAP Dev Stack Debian 12 Base Image"
LABEL org.opencontainers.image.description="Base Debian 12 image for ASAP Dev Stack with SSH and sudo setup"
LABEL org.opencontainers.image.source="https://github.com/ASAP-Initiative/asap-dev-stack.git"
