FROM fedora:41@sha256:c3643bda846169b342b400d4bbd1cb7022a7037e108b403a97305d1cb1644bcd

RUN dnf -y update \
    && dnf -y install openssh-server sudo supervisor \
    && dnf clean all

# Create 'asap' user with sudo privileges
RUN groupadd --system asap \
    && groupadd --system sudo \
    && adduser --system --shell /bin/bash --home /home/asap -g asap asap \
    && mkdir -p /home/asap/.ssh \
    && usermod -aG sudo asap \
    && sed -i -E 's/%sudo\s+ALL=\(ALL:ALL\) ALL/%sudo ALL=\(ALL:ALL\) NOPASSWD:ALL/g' /etc/sudoers

# Add SSH public key for 'asap' user
COPY id_ed25519.pub /home/asap/.ssh/authorized_keys
RUN chown -R asap:asap /home/asap/ \
    && chmod 700 /home/asap/.ssh \
    && chmod 600 /home/asap/.ssh/authorized_keys

# Requirements for SSH daemon
RUN ssh-keygen -A

# Copy supervisord configuration
COPY supervisord.conf /etc/supervisord.conf

ENTRYPOINT [ "/usr/bin/supervisord", "-c", "/etc/supervisord.conf" ]

LABEL org.opencontainers.image.title="ASAP Dev Stack Fedora 41 Base Image"
LABEL org.opencontainers.image.description="Base Fedora 41 image for ASAP Dev Stack with SSH and sudo setup"
LABEL org.opencontainers.image.source="https://github.com/ASAP-Initiative/asap-dev-stack.git"
