---
name: Lint Dockerfiles and docker-compose
permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Lint YAML files
        run: |
          yamllint -c scripts/.yamllint.yml docker-compose.yml

      - name: Lint Dockerfiles and docker-compose
        run: |
          cd scripts
          chmod +x lint.sh
          ./lint.sh
